### ISSUE TITLE
Sign in with GitHub 

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/opensourcer-client#10]
## TODO 
- [ ] Set up page routers and auth callback 
- [ ] Listen for github Oauth callback
- [ ] Send github oauth callback to server for jwt token 
- [ ] save jwt token in localstorage

--- 
## Some useful links 
```
https://github.com/login/oauth/authorize?client_id={}scope=user
```
